<a href="https://colab.research.google.com/github/Midmost/Cloud_AI_mobile_ios/blob/main/AI/01_MLP_And_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 

## Simple Keras 모델 생성/학습 - AND Function

In [ ]:
# 1. Numpy 가져오기
import numpy as np

print(np.__version__)

1.19.5


In [ ]:
# 2. 입력/출력 데이터 만들기

# csv = "/content/diabetes_data.csv"

x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[0],[0],[1]])

print(x)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [ ]:
# 3. Keras 패키지 가져오기
from tensorflow import keras 
from tensorflow.keras import layers

# 항상 버전을 맞춰주는 습관을 가지자
print(keras.__version__)

2.6.0


In [ ]:
# 4. Perceptron 모델 생성

# from keras.models import Sequential
# model = Sequential()

model = keras.Sequential()


model.add(layers.Dense(input_dim=2, units=1)) # 우리는 단일퍼셉트론을 만들거기 때문에 이게 입력층이자 출력층
model.add(layers.Activation('sigmoid'))

model.summary()
# model.add(Dense(12, input_dim=8, kernel_initializer='random_uniform'))

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 5. Compile - Optimizer, Loss function 설정
from keras.layers.core import Dense, Activation

sgd = keras.optimizers.SGD(learning_rate=0.1)
model.compile(loss = 'binary_crossentropy')


# from keras.optimizers import SGD 이거를 안쓰넴....

In [ ]:
# 6. 학습시키기

# history = model.fit(X_train, Y_train, batch_size=1, epochs=200, verbose=VERBOSE, validation_split=VALIDATION_SPLIT)
# batch_size 가 1이란건 한 번 풀고 답 확인하고 한다는 거 몇문제 풀고 답을 확인하는지를 보는 게 batch_size

history = model.fit(x, y, batch_size=1, epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7351
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7328
Epoch 3/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7314
Epoch 4/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7300
Epoch 5/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7288
Epoch 6/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7277
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7266
Epoch 8/200
4/4 [==============================] - 0s 4ms/step - loss: 0.7255
Epoch 9/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7244
Epoch 10/200
4/4 [==============================] - 0s 4ms/step - loss: 0.7234
Epoch 11/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7223
Epoch 12/200
4/4 [==============================] - 0s 3ms/step - loss: 0.7213
Epoch 13/200
4/4 [==============================] - 0s 3ms/st

In [ ]:
# 7. 모델 테스트하기
# score = model.evaluate(X_test, Y_test, verbose=0)
test_data = np.array([[0,1],[1,0],[1,1]])
result = model.predict(test_data)
print(result)

[[0.54204494]
 [0.40318096]
 [0.5622356 ]]


In [ ]:
# Parameter 확인
model.get_weights()

[array([[0.08166226],
        [0.6424686 ]], dtype=float32), array([-0.47389075], dtype=float32)]