<a href="https://colab.research.google.com/github/Midmost/Cloud_AI_mobile_ios/blob/main/AI/01_MLP_OR_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 

## Simple Keras 모델 생성/학습 - AND Function

In [1]:
# 1. Numpy 가져오기
import numpy as np

print(np.__version__)

1.19.5


In [2]:
# 2. 입력/출력 데이터 만들기

x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[1]])

print(x)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [3]:
# 3. Keras 패키지 가져오기
from tensorflow import keras 
from tensorflow.keras import layers

print(keras.__version__)

2.6.0


In [5]:
# 4. Perceptron 모델 생성
from keras.models import Sequential
model = Sequential()

model.add(layers.Dense(input_dim=2, units=1)) # 우리는 단일퍼셉트론을 만들거기 때문에 이게 입력층이자 출력층
model.add(layers.Activation('sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [11]:
# 5. Compile - Optimizer, Loss function 설정
sgd = keras.optimizers.SGD(learning_rate=0.1)
model.compile(loss ='binary_crossentropy', optimizer=sgd)


# from keras.optimizers import SGD 이거를 안쓰넴....

In [12]:
# 6. 학습시키기
history = model.fit(x, y, batch_size=1, epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 3ms/step - loss: 0.6668
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 0.6226
Epoch 3/200
4/4 [==============================] - 0s 2ms/step - loss: 0.5891
Epoch 4/200
4/4 [==============================] - 0s 2ms/step - loss: 0.5624
Epoch 5/200
4/4 [==============================] - 0s 2ms/step - loss: 0.5403
Epoch 6/200
4/4 [==============================] - 0s 2ms/step - loss: 0.5226
Epoch 7/200
4/4 [==============================] - 0s 2ms/step - loss: 0.5071
Epoch 8/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4940
Epoch 9/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4824
Epoch 10/200
4/4 [==============================] - 0s 2ms/step - loss: 0.4720
Epoch 11/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4630
Epoch 12/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4547
Epoch 13/200
4/4 [==============================] - 0s 2ms/st

In [16]:
# 7. 모델 테스트하기

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])
result = model.predict(test_data)
print(result)

[[0.22791561]
 [0.91586185]
 [0.90956825]
 [0.997311  ]]


In [17]:
# Parameter 확인
model.get_weights()

[array([[3.5284925],
        [3.6075232]], dtype=float32), array([-1.2201183], dtype=float32)]